//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDS_CONTEXT_EXTRACT             42
#define IDS_CONTEXT_EXTRACT_HELP        43
#define IDS_CONTEXT_COMPRESS            44
#define IDS_CONTEXT_COMPRESS_HELP       45
#define IDS_CONTEXT_OPEN                46
#define IDS_CONTEXT_OPEN_HELP           47
#define IDS_CONTEXT_TEST                48
#define IDS_CONTEXT_TEST_HELP           49
#define IDS_CONTEXT_CAPTION_HELP        50
#define IDS_CONTEXT_POPUP_CAPTION       51
#define IDS_METHOD_STORE                80
#define IDS_METHOD_NORMAL               81
#define IDS_METHOD_MAXIMUM              82
#define IDS_OPEN_TYPE_ALL_FILES         83
#define IDS_COMPRESS_SET_ARCHIVE_DIALOG_TITLE 84
#define IDS_COMPRESS_UPDATE_MODE_ADD    85
#define IDS_COMPRESS_UPDATE_MODE_UPDATE 86
#define IDS_COMPRESS_UPDATE_MODE_FRESH  87
#define IDS_COMPRESS_UPDATE_MODE_SYNCHRONIZE 88
#define IDS_CANT_UPDATE_ARCHIVE         89
#define IDS_PROGRESS_COMPRESSING        98
#define IDS_PROGRESS_TESTING            99
#define IDS_ERROR                       100
#define IDS_MESSAGE_NO_ERRORS           101
#define IDS_CONFIG_DIALOG_CAPTION       102
#define IDD_DIALOG_EXTRACT              137
#define IDB_DELETE                      149
#define IDD_DIALOG_COMPRESS             152
#define IDC_EXTRACT_COMBO_PATH          1044
#define IDC_EXTRACT_BUTTON_SET_PATH     1045
#define IDC_EXTRACT_RADIO_FULL_PATHNAMES 1046
#define IDC_EXTRACT_RADIO_CURRENT_PATHNAMES 1048
#define IDC_EXTRACT_RADIO_NO_PATHNAMES  1049
#define IDC_EXTRACT_RADIO_ASK_BEFORE_OVERWRITE 1050
#define IDC_EXTRACT_RADIO_OVERWRITE_WITHOUT_PROMPT 1051
#define IDC_EXTRACT_RADIO_SKIP_EXISTING_FILES 1052
#define IDC_EXTRACT_RADIO_SELECTED_FILES 1053
#define IDC_EXTRACT_RADIO_ALL_FILES     1054
#define IDC_EXTRACT_RADIO_AUTO_RENAME   1055
#define IDC_EXTRACT_PATH_MODE           1056
#define IDC_EXTRACT_OVERWRITE_MODE      1057
#define IDC_EXTRACT_FILES               1058
#define IDC_LIST1                       1067
#define IDC_COLUMN_EDIT_WIDTH           1068
#define IDC_EXTRACT_EDIT_PASSWORD       1068
#define IDC_COMPRESS_COMBO_ARCHIVE      1072
#define IDC_COMPRESS_BUTTON_SET_ARCHIVE 1073
#define IDC_COMPRESS_COMBO_METHOD       1074
#define IDC_COMPRESS_COMBO_UPDATE_MODE  1075
#define IDC_COMPRESS_COMBO_FORMAT       1076
#define IDC_COMPRESS_SFX                1090
#define IDC_COMPRESS_EDIT_PARAMETERS    1091
#define IDC_COMPRESS_SOLID              1092
#define IDC_STATIC_EXTRACT_EXTRACT_TO   1092
#define IDC_STATIC_COMPRESS_ARCHIVE     1097
#define IDC_STATIC_COMPRESS_FORMAT      1098
#define IDC_STATIC_COMPRESS_METHOD      1099
#define IDC_STATIC_COMPRESS_PARAMETERS  1100
#define IDC_STATIC_COMPRESS_UPDATE_MODE 1101
#define IDC_STATIC_COMPRESS_OPTIONS     1102
#define IDC_EXTRACT_PASSWORD            1106
#define IDC_COMPRESS_PASSWORD           1107
#define IDC_COMPRESS_EDIT_PASSWORD      1108

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
