#define IDS_CANNOT_CREATE_FOLDER  200
#define IDS_OPEN_IS_NOT_SUPORTED_ARCHIVE  201

#define IDS_MESSAGES_DIALOG_EXTRACT_MESSAGE_CRC  202
#define IDS_MESSAGES_DIALOG_EXTRACT_MESSAGE_DATA_ERROR  203
#define IDS_MESSAGES_DIALOG_EXTRACT_MESSAGE_UNSUPPORTED_METHOD  204
#define IDS_MESSAGES_DIALOG_EXTRACT_MESSAGE_CRC_ENCRYPTED  205
#define IDS_MESSAGES_DIALOG_EXTRACT_MESSAGE_DATA_ERROR_ENCRYPTED  206

#define IDS_EXTRACT_SET_FOLDER  207
#define IDS_MESSAGES_DIALOG_EXTRACT_MESSAGE_CANNOT_OPEN_FILE  208
#define IDS_PROGRESS_EXTRACTING  209

#define IDS_CANT_OPEN_ARCHIVE   103
#define IDS_CANT_OPEN_ENCRYPTED_ARCHIVE 104
