@echo off

rd /S /Q "CPP\7zip\bin32"
rd /S /Q "CPP\7zip\bin64"

rd /S /Q "C/Util/7zipInstall/O"
rd /S /Q "C/Util/7zipUninstall/O"
rd /S /Q "CPP/7zip/Bundles/Codec_lz4/O"
rd /S /Q "CPP/7zip/Bundles/Codec_lz5/O"
rd /S /Q "CPP/7zip/Bundles/Codec_zstdF/O"
rd /S /Q "CPP/7zip/Bundles/Format7z/O"
rd /S /Q "CPP/7zip/Bundles/Format7zF/O"
rd /S /Q "CPP/7zip/Bundles/SFXCon/O"
rd /S /Q "CPP/7zip/Bundles/SFXWin/O"
rd /S /Q "CPP/7zip/UI/Console/O"
rd /S /Q "CPP/7zip/UI/Explorer/O"
rd /S /Q "CPP/7zip/UI/FileManager/O"
rd /S /Q "CPP/7zip/UI/GUI/O"

rd /S /Q "C/Util/7zipInstall/AMD64"
rd /S /Q "C/Util/7zipUninstall/AMD64"
rd /S /Q "CPP/7zip/Bundles/Codec_lz4/AMD64"
rd /S /Q "CPP/7zip/Bundles/Codec_lz5/AMD64"
rd /S /Q "CPP/7zip/Bundles/Codec_zstdF/AMD64"
rd /S /Q "CPP/7zip/Bundles/Format7z/AMD64"
rd /S /Q "CPP/7zip/Bundles/Format7zF/AMD64"
rd /S /Q "CPP/7zip/Bundles/SFXCon/AMD64"
rd /S /Q "CPP/7zip/Bundles/SFXWin/AMD64"
rd /S /Q "CPP/7zip/UI/Console/AMD64"
rd /S /Q "CPP/7zip/UI/Explorer/AMD64"
rd /S /Q "CPP/7zip/UI/FileManager/AMD64"
rd /S /Q "CPP/7zip/UI/GUI/AMD64"

