#define IDD_MENU     2300
#define IDD_MENU_2  12300

#define IDX_SYSTEM_INTEGRATE_TO_CONTEXT_MENU  2301
#define IDX_SYSTEM_CASCADED_MENU              2302
#define IDT_SYSTEM_CONTEXT_MENU_ITEMS         2303
#define IDX_SYSTEM_ICON_IN_MENU               2304

#define IDL_SYSTEM_OPTIONS  100
