#define IDC_BUTTON_PAUSE                3
#define IDC_BUTTON_PROGRESS_PRIORITY    4
#define IDD_DIALOG_PROGRESS             500
#define IDS_PROGRESS_PAUSED             700
#define IDS_PROGRESS_FOREGROUND         701
#define IDS_PROGRESS_CONTINUE           702
#define IDS_PROGRESS_ASK_CANCEL         703
#define IDC_PROGRESS1                   1000
#define IDC_PROGRESS_ELAPSED            1002
#define IDC_PROGRESS_ELAPSED_VALUE      1003
#define IDC_PROGRESS_REMAINING          1004
#define IDC_PROGRESS_REMAINING_VALUE    1005
#define IDC_PROGRESS_SPEED              1006
#define IDC_PROGRESS_SPEED_VALUE        1007
#define IDC_PROGRESS_TOTAL              1008
#define IDC_PROGRESS_TOTAL_VALUE        1009
#define IDC_PROGRESS_FILE_NAME          1010

#define IDC_PROGRESS_FILES              1012
#define IDC_PROGRESS_FILES_VALUE        1013
#define IDC_PROGRESS_RATIO              1014
#define IDC_PROGRESS_RATIO_VALUE        1015
#define IDC_PROGRESS_PACKED             1016
#define IDC_PROGRESS_PACKED_VALUE       1017
#define IDC_PROGRESS_UNPACKED           1018
#define IDC_PROGRESS_UNPACKED_VALUE     1019
