#define IDS_PROPERTY_PATH                3
#define IDS_PROPERTY_NAME                4
#define IDS_PROPERTY_EXTENSION           5
#define IDS_PROPERTY_IS_FOLDER           6
#define IDS_PROPERTY_SIZE                7
#define IDS_PROPERTY_PACKED_SIZE         8
#define IDS_PROPERTY_ATTRIBUTES          9
#define IDS_PROPERTY_CREATION_TIME      10
#define IDS_PROPERTY_LAST_ACCESS_TIME   11
#define IDS_PROPERTY_LAST_WRITE_TIME    12
#define IDS_PROPERTY_SOLID              13
#define IDS_PROPERTY_C0MMENTED          14
#define IDS_PROPERTY_ENCRYPTED          15
#define IDS_PROPERTY_DICTIONARY_SIZE    16
#define IDS_PROPERTY_SPLIT_BEFORE       17
#define IDS_PROPERTY_SPLIT_AFTER        18
#define IDS_PROPERTY_CRC                19
#define IDS_PROPERTY_FILE_TYPE          20
#define IDS_PROPERTY_ANTI               21
#define IDS_PROPERTY_METHOD             22
#define IDS_PROPERTY_HOST_OS            23
#define IDS_PROPERTY_FILE_SYSTEM        24
#define IDS_PROPERTY_USER               25
#define IDS_PROPERTY_GROUP              26
#define IDS_PROPERTY_BLOCK              27
#define IDS_PROPERTY_COMMENT            28
#define IDS_PROPERTY_POSITION           29
#define IDS_PROPERTY_PREFIX             30
#define IDS_PROPERTY_FOLDERS            31
#define IDS_PROPERTY_FILES              32
#define IDS_PROPERTY_VERSION            33
#define IDS_PROPERTY_VOLUME             34
#define IDS_PROPERTY_IS_VOLUME          35
#define IDS_PROPERTY_OFFSET             36
#define IDS_PROPERTY_LINKS              37
#define IDS_PROPERTY_NUM_BLOCKS         38
#define IDS_PROPERTY_NUM_VOLUMES        39
