#define IDS_CANNOT_CREATE_FOLDER  200
#define IDS_OPEN_IS_NOT_SUPORTED_ARCHIVE  201

#define IDS_MESSAGES_DIALOG_EXTRACT_MESSAGE_CRC  202
#define IDS_MESSAGES_DIALOG_EXTRACT_MESSAGE_DATA_ERROR  203
#define IDS_MESSAGES_DIALOG_EXTRACT_MESSAGE_UNSUPPORTED_METHOD  204

#define IDS_EXTRACT_SET_FOLDER  205
#define IDS_MESSAGES_DIALOG_EXTRACT_MESSAGE_CANNOT_OPEN_FILE  206
#define IDS_PROGRESS_EXTRACTING  207
