//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDD_DIALOG_COMPRESS             152
#define IDC_STATIC_COMPRESS_MEMORY      1022
#define IDC_STATIC_COMPRESS_MEMORY_DE   1023
#define IDC_STATIC_COMPRESS_MEMORY_VALUE 1027
#define IDC_STATIC_COMPRESS_MEMORY_DE_VALUE 1028
#define IDC_COMPRESS_COMBO_ARCHIVE      1072
#define IDC_COMPRESS_BUTTON_SET_ARCHIVE 1073
#define IDC_COMPRESS_COMBO_LEVEL        1074
#define IDC_COMPRESS_COMBO_UPDATE_MODE  1075
#define IDC_COMPRESS_COMBO_FORMAT       1076
#define IDC_COMPRESS_COMBO_VOLUME       1077
#define IDC_COMPRESS_COMBO_METHOD       1078
#define IDC_COMPRESS_COMBO_DICTIONARY   1079
#define IDC_COMPRESS_COMBO_ORDER        1080
#define IDC_COMPRESS_SFX                1090
#define IDC_COMPRESS_EDIT_PARAMETERS    1091
#define IDC_COMPRESS_SOLID              1092
#define IDC_COMPRESS_MULTI_THREAD       1093
#define IDC_STATIC_COMPRESS_ARCHIVE     1097
#define IDC_STATIC_COMPRESS_FORMAT      1098
#define IDC_STATIC_COMPRESS_LEVEL       1099
#define IDC_STATIC_COMPRESS_PARAMETERS  1100
#define IDC_STATIC_COMPRESS_UPDATE_MODE 1101
#define IDC_STATIC_COMPRESS_OPTIONS     1102
#define IDC_STATIC_COMPRESS_VOLUME      1103
#define IDC_STATIC_COMPRESS_METHOD      1104
#define IDC_STATIC_COMPRESS_DICTIONARY  1105
#define IDC_STATIC_COMPRESS_ORDER       1106
#define IDC_COMPRESS_PASSWORD           1107
#define IDC_COMPRESS_EDIT_PASSWORD      1108
#define IDC_COMPRESS_CHECK_SHOW_PASSWORD 1109
#define IDC_COMPRESS_CHECK_ENCRYPT_FILE_NAMES 1110

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1110
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
