#define IDD_DIALOG_EXTRACT              137

#define IDC_STATIC_EXTRACT_EXTRACT_TO   1020
#define IDC_EXTRACT_COMBO_PATH          1021
#define IDC_EXTRACT_BUTTON_SET_PATH     1022


#define IDC_EXTRACT_PATH_MODE           1040
#define IDC_EXTRACT_RADIO_FULL_PATHNAMES 1041
#define IDC_EXTRACT_RADIO_CURRENT_PATHNAMES 1042
#define IDC_EXTRACT_RADIO_NO_PATHNAMES  1043

#define IDC_EXTRACT_OVERWRITE_MODE      1050
#define IDC_EXTRACT_RADIO_ASK_BEFORE_OVERWRITE 1051
#define IDC_EXTRACT_RADIO_OVERWRITE_WITHOUT_PROMPT 1052
#define IDC_EXTRACT_RADIO_SKIP_EXISTING_FILES 1053
#define IDC_EXTRACT_RADIO_SELECTED_FILES 1054
#define IDC_EXTRACT_RADIO_ALL_FILES     1055
#define IDC_EXTRACT_RADIO_AUTO_RENAME   1056
#define IDC_EXTRACT_RADIO_AUTO_RENAME_EXISTING 1057


#define IDC_EXTRACT_FILES               1060

#define IDC_EXTRACT_PASSWORD            1100
#define IDC_EXTRACT_EDIT_PASSWORD       1101
#define IDC_EXTRACT_CHECK_SHOW_PASSWORD 1102

