//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//

#define IDC_EXTRACT_COMBO_PATH          1044
#define IDC_EXTRACT_BUTTON_SET_PATH     1045
#define IDC_EXTRACT_RADIO_FULL_PATHNAMES 1046
#define IDC_EXTRACT_RADIO_CURRENT_PATHNAMES 1048
#define IDC_EXTRACT_RADIO_NO_PATHNAMES  1049
#define IDC_EXTRACT_RADIO_ASK_BEFORE_OVERWRITE 1050
#define IDC_EXTRACT_RADIO_OVERWRITE_WITHOUT_PROMPT 1051
#define IDC_EXTRACT_RADIO_SKIP_EXISTING_FILES 1052
#define IDC_EXTRACT_RADIO_SELECTED_FILES 1053
#define IDC_EXTRACT_RADIO_ALL_FILES     1054
#define IDC_EXTRACT_RADIO_AUTO_RENAME   1055
#define IDC_EXTRACT_PATH_MODE           1056
#define IDC_EXTRACT_OVERWRITE_MODE      1057
#define IDC_EXTRACT_FILES               1058
#define IDC_EXTRACT_EDIT_PASSWORD       1068
#define IDC_EXTRACT_PASSWORD            1106
#define IDC_EXTRACT_CHECK_SHOW_PASSWORD 1109
#define IDC_STATIC_EXTRACT_EXTRACT_TO   1092


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1110
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
