//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by resource.rc
//
#define IDS_FILE_MODIFIED               600
#define IDS_FILE_SIZE                   601

#define IDD_DIALOG_OVERWRITE             502

#define IDC_STATIC_OVERWRITE_HEADER     1000

#define IDC_STATIC_OVERWRITE_QUESTION_BEGIN 1001
#define IDC_STATIC_OVERWRITE_QUESTION_END 1002

#define IDC_STATIC_OVERWRITE_OLD_FILE_ICON 1003
#define IDC_STATIC_OVERWRITE_NEW_FILE_ICON 1004

#define IDC_STATIC_OVERWRITE_OLD_FILE_SIZE_TIME 1005
#define IDC_STATIC_OVERWRITE_NEW_FILE_SIZE_TIME 1006

#define IDC_BUTTON_OVERWRITE_YES_TO_ALL 1010
#define IDC_BUTTON_OVERWRITE_NO_TO_ALL  1011
#define IDC_BUTTON_OVERWRITE_AUTO_RENAME 1012



// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
